# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7257c447deb3518c37a464b2abb08e5537ce9729f319b434879822b505d47341238ae7491dc41a7df4b781f84be1c337b3ee859be8714d315cd444468df6578d

test:
  secret_key_base: be0488e12cabd78af002624beb0557742d6e9917248318808ddb260f4b672e1feb0e6f90430cf09da8b930d0c150688816c77eec1e70e9efb1b2a33f32e188dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
